---
title: Instrukcja throw
slug: >-
  orphaned/Web/JavaScript/Guide/Obsolete_Pages/Przewodnik_po_języku_JavaScript_1.5/Instrukcje_obsługi_wyjątków/Instrukcja_throw
tags:
  - JavaScript
  - Przewodnik_JavaScript
  - Wszystkie_kategorie
original_slug: >-
  Web/JavaScript/Guide/Obsolete_Pages/Przewodnik_po_języku_JavaScript_1.5/Instrukcje_obsługi_wyjątków/Instrukcja_throw
---
<div class="noinclude">
 <h3 id="Instrukcja_throw" name="Instrukcja_throw">Instrukcja throw</h3>
 <p>Użyj instrukcji <code>throw</code>, aby wywołać wyjątek. Gdy wywołujesz wyjątek, określasz wyrażenie zawierające wartość, która ma zostać wywołana:</p>
 <pre class="eval">throw wyrazenie;
</pre>
 <p>Możesz wywołać dowolne wyrażenie, nie tylko wyrażenie konkretnego typu. Poniższy kod wywołuje kilka wyjątków różnych typów:</p>
 <pre class="eval">throw &quot;Error2&quot;;
throw 42;
throw true;
throw {toString: function() { return &quot;Jestem obiektem!&quot;; } };
</pre>
 <div class="note notecard">
  <b>Uwaga:</b> Możesz określić obiekt podczas wywoływania wyjątku. Można się wtedy odnieść do własności obiektu w bloku <code>catch</code>. Poniższy przykład tworzy obiekt <code>myUserException</code> typu <code>UserException</code> i używa go w instrukcji throw.</div>
 <p> </p>
 <pre class="eval">// Utwórz obiekt typu UserException
function UserException (message)
{
  this.message=message;
  this.name=&quot;UserException&quot;;
}

// Przekonwertuj wyjątek do ładnego łańcucha znaków,
// gdy ma on zostać użyty jako łańcuch znaków (np. przez konsolę błędów)
UserException.prototype.toString = function ()
{
  return this.name + &apos;: &quot;&apos; + this.message + &apos;&quot;&apos;;
}

// Utwórz instancję typu obiektu i wywołaj ją
throw new UserException(&quot;Za duża wartość&quot;);
</pre>
 <div class="noinclude">
  <p></p><div style="text-align: right;" class="prevnext">
    <p><a style="float: left;" href="/pl/docs/Przewodnik_po_języku_JavaScript_1.5:Instrukcje_obsługi_wyjątków" class="button">« Poprzedni</a><a href="/pl/docs/Przewodnik_po_języku_JavaScript_1.5:Instrukcje_obsługi_wyjątków:Instrukcja_try...catch" class="button">Następny  »</a></p>
</div><p></p>
 </div>
</div>
<p> </p>
